### ISSUE TITLE
undefined symbol: PyInt_FromLong

### ISSUE THREAD

**Issue by Bebotron** [HQSquantumsimulations/PyQuEST-cffi#17]
I don't know if this is too broad of an issue to warrant being posted here, but it seems the error stems from a quest file so any help is appreciated.

After installing this library with `pip3 install pyquest_cffi`, I'm getting a successful install message (I can post the whole thing if I need to). But when I try to run the example `QuEST_example_in_python.py`, I get the following errors for the `from pyquest_cffi import object` lines
```
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyquest_cffi import ops
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/.local/lib/python3.6/site-packages/pyquest_cffi/__init__.py", line 25, in <module>
    from pyquest_cffi.questlib import quest
  File "/home/david/.local/lib/python3.6/site-packages/pyquest_cffi/questlib/__init__.py", line 19, in <module>
    from ._quest import ffi as ffi_quest
ImportError: /home/david/.local/lib/python3.6/site-packages/pyquest_cffi/questlib/_quest.so: undefined symbol: PyInt_FromLong
>>>
```
A couple notes that may be relevant:

1. I am running Windows10, but the installing pyquest_cffi on Windows was a bit too much of a pain in getting cffi working. So I'm doing this in WSL (Windows Subsystem for Linux), which initially seemed to work with the successful install, but is evidently also not working. Also this error message seems like it should be easier to trace so for now I think sticking with WSL is not a bad idea.

2. When trying `pip install pyquest_cffi` using Python2.7, I can't even get a "successful" install with a plethora of errors. So I'm using Python3.6, which installs without errors initially.

**Comment by nfwvogt** [comment]
Hi and sorry for the long response time, the issue report totally slipped by us.
We will have a look, however we don't have windows machines readily available, so I can't guarantee we will be able to reproduce this error.
To give us a better idea are you using WSL 1 or WSL 2? 
Also which linux distro do you use in the WSL? The standard ubuntu one?

**Comment by Bebotron** [comment]
It looks like I have WSL 1, and I am using Ubuntu 18.04. I could try upgrading to WSL 2 and see if that works.

Additionally, I managed a successful, working install in a conda environment in a linux server using all updated python. So I'll also try updating my python libraries in my windows machine and see if that helps.

**Comment by nfwvogt** [comment]
Ok, thank you for the information.
As I said I can't test it on a windows machine at the moment, but from a few tests I ran on a fresh ubuntu docker image, there might be a problem picking out the right python2/python3 version during installation. 
We are looking into this, but in the meantime I would try using the following workaround:
Install the command line anaconda python distribution in you WSL linux distribution. That lets everything default to python3 and so far we haven't had problems with pyquest-cffi when using anaconda on ubuntu 18.04 based machines.
I can't test how that interacts with windows but if it does not work you could also try using WSL2 instead of WSL1 to install anaconda and pyquest.
As far as I understand WSL2 is more a less a complete virtualized linux without all the wrapper calls of WSL1, so I should be closer to setups we have already tested.

**Comment by nfwvogt** [comment]
We have a new release out that fixes a problem with mixed python2/python3 environments on ubuntu.
Could you try if that runs for you?

**Comment by Bebotron** [comment]
This works for Ubuntu 18.04 on WSL1 using python3, having installed with `pip3`. Thanks!

Would be nice to get this working on Windows, but this should work for everything I'm doing. I'll leave that for a different issue.
